#!/bin/bash
#SBATCH --partition batch
#SBATCH --ntasks=1
#SBATCH --time=48:00:00
#SBATCH --mem=3gb

ml HpcGridRunner/1.0.2
ml BLAST+/2.12.0-gompi-2020b

hpc_FASTA_GridRunner.pl --grid_conf=$HPCGR_CONF_DIR/sapelo_1c_3g.conf --cmd_template "blastp -query __QUERY_FILE__ -db /db/ncbiblast/20220502/swissprot -max_target_seqs 1 -max_hsps 1 -outfmt '6 qseqid sseqid stitle pident length mismatch gapopen qstart qend sstart send evalue bitscore' -evalue 1e-20 -num_threads 1" --seqs_per_bin 100 --query_fasta [QUERY FILE GOES HERE]  --out_dir results/DEGlistsWithBLASTdescriptions/swissprotBLAST
