#!/bin/bash
#SBATCH --job-name=kallisto_quant
#SBATCH --partition=batch
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=2
#SBATCH --mem=80gb
#SBATCH --time=0:20:00
#SBATCH --output=%s_kallisto_quant.%j.out
#SBATCH --error=%s_kallisto_quant.%j.err
#SBATCH --array=1-48

# put input file names in "input.txt", all pairs you want to use-per kallisto command on the same line (space-separated)
files=$(awk "NR==${SLURM_ARRAY_TASK_ID}" kallisto_input.txt)

# this grabs all the letters up to the first underscore in whatever the $file variable evaluates as
output=$(awk -F _ '{print $2}' $files)

module load kallisto/0.46.1-foss-2019b

# name output files whatever you want, as long as ${output} is somewhere in the name
kallisto quant -i VFT.idx -o ${SLURM_ARRAY_TASK_ID}_kallistoquant -b 100 \
$files
